// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYR5FZwwIJn9Umjgt0wU6nMBFIEMXHUY',
    appId: '1:894914362548:web:fd3d411e5f3c80e518ebe1',
    messagingSenderId: '894914362548',
    projectId: 'nutriscan-ce2a3',
    authDomain: 'nutriscan-ce2a3.firebaseapp.com',
    storageBucket: 'nutriscan-ce2a3.firebasestorage.app',
    measurementId: 'G-VMNPWC81DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-DHdSRjuHgCGjj7ujLhFKpO_Gg2uvAVA',
    appId: '1:894914362548:android:8463c58691632ff518ebe1',
    messagingSenderId: '894914362548',
    projectId: 'nutriscan-ce2a3',
    storageBucket: 'nutriscan-ce2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMtPjCweZGe2JEADL4rpr7vO3aMH5rZQ',
    appId: '1:894914362548:ios:7939d8c785dd219818ebe1',
    messagingSenderId: '894914362548',
    projectId: 'nutriscan-ce2a3',
    storageBucket: 'nutriscan-ce2a3.firebasestorage.app',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMtPjCweZGe2JEADL4rpr7vO3aMH5rZQ',
    appId: '1:894914362548:ios:7939d8c785dd219818ebe1',
    messagingSenderId: '894914362548',
    projectId: 'nutriscan-ce2a3',
    storageBucket: 'nutriscan-ce2a3.firebasestorage.app',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhYR5FZwwIJn9Umjgt0wU6nMBFIEMXHUY',
    appId: '1:894914362548:web:cac8cb642eea15f218ebe1',
    messagingSenderId: '894914362548',
    projectId: 'nutriscan-ce2a3',
    authDomain: 'nutriscan-ce2a3.firebaseapp.com',
    storageBucket: 'nutriscan-ce2a3.firebasestorage.app',
    measurementId: 'G-51B6NZVF58',
  );
}
